<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\org\models\base;

use Yii;

/**
 * This is the base-model class for table "cn_city".
 *
 * @property integer $city_id
 * @property string $city_name
 * @property integer $province_id
 * @property string $first_letter
 *
 * @property \backend\modules\org\models\CnProvince $province
 * @property \backend\modules\org\models\CnRegion[] $cnRegions
 * @property string $aliasModel
 */
abstract class CnCity extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cn_city';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('org');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['city_id', 'city_name', 'province_id'], 'required'],
            [['city_id', 'province_id'], 'integer'],
            [['city_name'], 'string', 'max' => 50],
            [['first_letter'], 'string', 'max' => 20],
            [['city_id'], 'unique'],
            [['province_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\org\models\CnProvince::className(), 'targetAttribute' => ['province_id' => 'province_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'city_id' => Yii::t('models', 'City ID'),
            'city_name' => Yii::t('models', 'City Name'),
            'province_id' => Yii::t('models', 'Province ID'),
            'first_letter' => Yii::t('models', 'First Letter'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProvince()
    {
        return $this->hasOne(\backend\modules\org\models\CnProvince::className(), ['province_id' => 'province_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCnRegions()
    {
        return $this->hasMany(\backend\modules\org\models\CnRegion::className(), ['city_id' => 'city_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\org\models\query\CnCityQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\org\models\query\CnCityQuery(get_called_class());
    }


}
