<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\org\models\base;

use Yii;

/**
 * This is the base-model class for table "cn_province".
 *
 * @property integer $province_id
 * @property string $province_name
 *
 * @property \backend\modules\org\models\CnCity[] $cnCities
 * @property string $aliasModel
 */
abstract class CnProvince extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cn_province';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('org');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['province_id', 'province_name'], 'required'],
            [['province_id'], 'integer'],
            [['province_name'], 'string', 'max' => 50],
            [['province_id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'province_id' => Yii::t('models', 'Province ID'),
            'province_name' => Yii::t('models', 'Province Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCnCities()
    {
        return $this->hasMany(\backend\modules\org\models\CnCity::className(), ['province_id' => 'province_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\org\models\query\CnProvinceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\org\models\query\CnProvinceQuery(get_called_class());
    }


}
