<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\org\models\base;

use Yii;

/**
 * This is the base-model class for table "cn_region".
 *
 * @property integer $region_id
 * @property string $region_name
 * @property integer $city_id
 *
 * @property \backend\modules\org\models\CnCity $city
 * @property \backend\modules\org\models\CnTown[] $cnTowns
 * @property \backend\modules\org\models\CnZipcode[] $cnZipcodes
 * @property string $aliasModel
 */
abstract class CnRegion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cn_region';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('org');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['region_id', 'region_name'], 'required'],
            [['region_id', 'city_id'], 'integer'],
            [['region_name'], 'string', 'max' => 50],
            [['region_id'], 'unique'],
            [['city_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\org\models\CnCity::className(), 'targetAttribute' => ['city_id' => 'city_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'region_id' => Yii::t('backend', 'Region ID'),
            'region_name' => Yii::t('backend', 'Region Name'),
            'city_id' => Yii::t('backend', 'City ID'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'region_name' => Yii::t('backend', '地区名称'),
            'city_id' => Yii::t('backend', '父地区ID'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCity()
    {
        return $this->hasOne(\backend\modules\org\models\CnCity::className(), ['city_id' => 'city_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCnTowns()
    {
        return $this->hasMany(\backend\modules\org\models\CnTown::className(), ['region_id' => 'region_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCnZipcodes()
    {
        return $this->hasMany(\backend\modules\org\models\CnZipcode::className(), ['region_id' => 'region_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\org\models\query\CnRegionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\org\models\query\CnRegionQuery(get_called_class());
    }


}
