<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\org\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "order".
 *
 * @property integer $order_id
 * @property integer $org_id
 * @property integer $user_id
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $created_at
 *
 * @property \backend\modules\org\models\Organization $org
 * @property \backend\modules\org\models\OrderAmount[] $orderAmounts
 * @property string $aliasModel
 */
abstract class Order extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('org');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::class,
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::class,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['org_id', 'user_id'], 'integer'],
            [['org_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\org\models\Organization::className(), 'targetAttribute' => ['org_id' => 'org_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'order_id' => Yii::t('backend', 'Order ID'),
            'org_id' => Yii::t('backend', 'Org ID'),
            'user_id' => Yii::t('backend', 'User ID'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'created_at' => Yii::t('backend', 'Created At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrg()
    {
        return $this->hasOne(\backend\modules\org\models\Organization::className(), ['org_id' => 'org_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderAmounts()
    {
        return $this->hasMany(\backend\modules\org\models\OrderAmount::className(), ['order_id' => 'order_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\org\models\query\OrderQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\org\models\query\OrderQuery(get_called_class());
    }


}
