<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "user_profile".
 *
 * @property integer $user_id
 * @property string $firstname
 * @property string $middlename
 * @property string $lastname
 * @property string $avatar_path
 * @property string $avatar_base_url
 * @property string $locale
 * @property integer $gender
 *
 * @property \backend\modules\crud\models\User $user
 * @property string $aliasModel
 */
abstract class UserProfile extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_profile';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['locale'], 'required'],
            [['gender'], 'integer'],
            [['firstname', 'middlename', 'lastname', 'avatar_path', 'avatar_base_url'], 'string', 'max' => 255],
            [['locale'], 'string', 'max' => 32],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\crud\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'user_id' => Yii::t('models', 'User ID'),
            'firstname' => Yii::t('models', 'Firstname'),
            'middlename' => Yii::t('models', 'Middlename'),
            'lastname' => Yii::t('models', 'Lastname'),
            'avatar_path' => Yii::t('models', 'Avatar Path'),
            'avatar_base_url' => Yii::t('models', 'Avatar Base Url'),
            'locale' => Yii::t('models', 'Locale'),
            'gender' => Yii::t('models', 'Gender'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\backend\modules\crud\models\User::className(), ['id' => 'user_id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\crud\models\query\UserProfileQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\crud\models\query\UserProfileQuery(get_called_class());
    }


}
