<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\org\controllers\base;

use backend\modules\org\models\CnProvince;
    use backend\modules\org\models\search\CnProvince as CnProvinceSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* CnProvinceController implements the CRUD actions for CnProvince model.
*/
class CnProvinceController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all CnProvince models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new CnProvinceSearch;
    $dataProvider = $searchModel->search($_GET);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]);
}

/**
* Displays a single CnProvince model.
* @param integer $province_id
*
* @return mixed
*/
public function actionView($province_id)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($province_id),
]);
}

/**
* Creates a new CnProvince model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new CnProvince;

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'province_id' => $model->province_id]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing CnProvince model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $province_id
* @return mixed
*/
public function actionUpdate($province_id)
{
$model = $this->findModel($province_id);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing CnProvince model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $province_id
* @return mixed
*/
public function actionDelete($province_id)
{
try {
$this->findModel($province_id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$province_id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the CnProvince model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $province_id
* @return CnProvince the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($province_id)
{
if (($model = CnProvince::findOne($province_id)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
